"""empty message

Revision ID: 1a42efff87c0
Revises: 5ef8d06fecc2
Create Date: 2021-09-29 20:54:36.461951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a42efff87c0'
down_revision = '5ef8d06fecc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_date', sa.String(), nullable=True))
    op.drop_column('movies', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('movies', 'release_date')
    # ### end Alembic commands ###
