"""empty message

Revision ID: f5463230f113
Revises: 1a42efff87c0
Create Date: 2021-10-03 01:13:15.916090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5463230f113'
down_revision = '1a42efff87c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('movies', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('actors', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
